# Generated by Django 6.0.6 on 2026-07-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='fecha_estado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='fecha_prioridad',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='usuario_accion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
