# Generated by Django 6.0.6 on 2026-07-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0002_reclamo_eliminado_reclamo_fecha_eliminacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamoEliminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reclamo_id', models.IntegerField()),
                ('fecha_eliminacion', models.DateTimeField()),
                ('usuario_accion', models.CharField(max_length=100)),
            ],
        ),
    ]
